name: docker bastion
on:
  workflow_dispatch:
jobs:
  docker-bastion:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@v5
    - name: terraform install
      uses: hashicorp/setup-terraform@v3
    - name: terraform init
      run: terraform init
    - name: "Configure AWS Credentials" Action for GitHub Actions
      uses: aws-actions/configure-aws-credentials@v6.2.3

    
        