name: docker bastion
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  docker-bastion:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@v5
    - name: terraform install
      uses: hashicorp/setup-terraform@v3
    - name: terraform init
      run: terraform init
    - name: Configure AWS Credentials for China region audience
      uses: aws-actions/configure-aws-credentials@v6.2.3
      with:
        audience: sts.amazonaws.com.cn
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
    - name: Test AWS Credentails
      run: aws sts get-caller-identity
      

    
        